/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class Lovehoroscope extends javax.swing.JFrame {

    /**
     * Creates new form Lovehoroscope
     */
    public Lovehoroscope() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdbMon = new javax.swing.JRadioButton();
        rdbTues = new javax.swing.JRadioButton();
        rdbWed = new javax.swing.JRadioButton();
        rdbThurs = new javax.swing.JRadioButton();
        rdbFri = new javax.swing.JRadioButton();
        rdbSatur = new javax.swing.JRadioButton();
        rdbSun = new javax.swing.JRadioButton();
        btnPredict = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarCharacter = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarCharacterLove = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        lblPerson = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Love Horoscope");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("ทำนายดวงความรักตามวันเกิด");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel2.setText("วันเกิด");

        buttonGroup1.add(rdbMon);
        rdbMon.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rdbMon.setText("วันจันทร์");

        buttonGroup1.add(rdbTues);
        rdbTues.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rdbTues.setText("วันอังคาร");

        buttonGroup1.add(rdbWed);
        rdbWed.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rdbWed.setText("วันพุธ");

        buttonGroup1.add(rdbThurs);
        rdbThurs.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rdbThurs.setText("วันพฤหัสบดี");

        buttonGroup1.add(rdbFri);
        rdbFri.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rdbFri.setText("วันศุกร์");

        buttonGroup1.add(rdbSatur);
        rdbSatur.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rdbSatur.setText("วันเสาร์");

        buttonGroup1.add(rdbSun);
        rdbSun.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rdbSun.setText("วันอาทิตย์");

        btnPredict.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPredict.setText("ทำนาย");
        btnPredict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPredictActionPerformed(evt);
            }
        });

        tarCharacter.setColumns(20);
        tarCharacter.setRows(5);
        jScrollPane1.setViewportView(tarCharacter);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel3.setText("นิสัย");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel4.setText("นิสัยเวลามีความรัก");

        tarCharacterLove.setColumns(20);
        tarCharacterLove.setRows(5);
        jScrollPane2.setViewportView(tarCharacterLove);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel5.setText("ระดับความคลั่งรัก");

        lblPerson.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblPerson.setForeground(new java.awt.Color(255, 51, 0));
        lblPerson.setText("0 %");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(97, 97, 97)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdbThurs)
                                            .addGap(34, 34, 34)
                                            .addComponent(rdbFri)
                                            .addGap(27, 27, 27)
                                            .addComponent(rdbSatur))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdbSun)
                                            .addGap(62, 62, 62)
                                            .addComponent(btnPredict, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(rdbMon))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(jScrollPane2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdbTues)
                        .addGap(18, 18, 18)
                        .addComponent(rdbWed)
                        .addGap(70, 70, 70)))
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addComponent(lblPerson)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdbMon)
                    .addComponent(rdbTues)
                    .addComponent(rdbWed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdbFri)
                        .addComponent(rdbSatur))
                    .addComponent(rdbThurs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbSun)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnPredict)))
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPerson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPredictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPredictActionPerformed
        if (rdbMon.isSelected()) {
            tarCharacter.setText("ปกติคนที่เกิดวันนี้เป็นคนที่ค่อนข้างแพรวพราว\nเป็นคนที่ค่อนข้างจะรักอิสระ \nดูเป็นคนเจ้าชู้ไม่รู้ตัว \nเพราะเป็นคนมีเสน่ห์ วางตัวดี");
            tarCharacterLove.setText("ถ้ามีความรักขึ้นมาล่ะก็เหมือนเป็นคนละคน!\nจากเสีอตัวใหญ่พอมีแฟนแล้วจะกลายเป็นแมวน้อย\nขี้อ้อน เอาใจ อยากได้อะไรจัดให้ทุกอย่าง\nงอแงกับแฟนเพราะอยากเรียกร้องความสนใจ\nถ้าคบกันแล้วก็อยากให้ดูแลเอาอกเอาใจซึ่งกันและกัน\nมือถือนี่ถ้าไม่ล็อกรหัสก็เรียบร้อย!\nเพราะคนเกิดวันนี้จะแอบหึง แอบส่องทุกอย่าง\nแฟนไปไหน ทำอะไร อยู่กับใคร รู้หมด!\nแต่คนที่เกิดวันจันทร์ถึงจะมีแฟนยังไงก็ยังไม่ทิ้งเพื่อน\nถ้าอีกฝ่ายเข้าใจไม่คิดมากก็คบกันได้ยาวๆ จ้า");
            lblPerson.setText("90%");
        } else if (rdbTues.isSelected()) {
            tarCharacter.setText("คนเกิดวันนี้เป็นพ่อแม่บุญทุ่มเวลารักใครจะจริงจังมากระดับสิบ!\nเป็นคนใจร้อนตอบช้า 5 นาทีจะรู้สึกใจหายแล้ว\nว่าเราพูดอะไรผิดไปไหมนะ? หรือว่าเขาไม่อยากคุยกับเราหรือเปล่า?\nหรือว่าเกิดเหตุร้ายอะไรขึ้น เอ๊ะ!\nหรือว่าแอบคุยกับคนอื่น");
            tarCharacterLove.setText("ถ้าอยู่ในช่วงอินเลิฟแล้วจะอารมณ์ดีทั้งวัน\nยิ้มคนเดียว เป็นคนติดแฟน อยากอยู่ด้วยตลอดเวลา\nเธออยู่ที่ไหน จะไปอยู่ตรงหน้า จะไปหาแน่ๆ!\nและค่อนข้างคาดหวังในตัวคนรักมากๆ\nถ้าให้ 100 ต้องได้กลับมา 100 ชอบอะไรที่แฟร์ๆ\nถ้าไม่แฟร์ก็หาใหม่ ชอบความตื่นเต้นท้าทาย\nถ้าอีกฝ่ายเล่นตัวนิดหน่อย เข้าหาบ้าง เอาใจก่อนบ้าง\nแกล้งไม่ตอบบ้าง ยิ่งตื่นเต้น ยิ่งถ้าอีกฝ่ายใส่ใจ\nและเข้าใจในตัวของคนที่เกิดวันอังคาร\nรับรองว่ารักจนมูฟออนไปไหนไม่ได้!");
            lblPerson.setText("100%");
        } else if (rdbWed.isSelected()) {
            tarCharacter.setText("คารมดีเป็นที่ 1 ตบมุขโบ๊ะบ๊ะได้ ทันคน เทคนิคอ่อยชั้นครู\nแพรวพราวพอ ๆ กับคนเกิดวันจันทร์ เป็นคนที่ค่อยๆ ดูค่อยๆ\nเก็บข้อมูลฝ่ายตรงข้าม ไม่วู่วาม ชอบนะ\nแต่ไม่แสดงออกตรง ๆ รอจนกว่าจะแน่ใจจริงๆ\nแล้วถึงจะตกลงเป็นแฟน");
            tarCharacterLove.setText("เป็นคนที่รักใครแล้วรักจริง โรแมนติก\nเรื่องเล็กๆน้อยก็จำได้ เอาใจใส่แฟนหรือคนรักมาก\nแต่ข้อเสียของคนที่เกิดวันนี้เป็นเพราะอีโก้ที่สูงเสียดฟ้า\nอาจจะทำให้เรื่องราวที่มันไม่ได้มีอะไรเลยพังได้ง่ายๆ\nเพราะความมีอีโก้ของตัวเอง เวลาโกรธมาก็จะใช้คำพูดที่ไม่ค่อยดี\nเป็นคนคาดหวังกับความรักสูง คิดมาก ขี้หึง ขี้ระแวง\nแล้วพอไม่ได้ตามที่หวังก็อาจจะพาลเบื่อได้ง่ายๆ\nแนะนำให้ใจเย็นๆและลดความคาดหวังกับอีโก้ลงนิดหน่อย\nจะทำให้ความรักไปได้ดี");
            lblPerson.setText("50%");
        } else if (rdbThurs.isSelected()) {
            tarCharacter.setText("ภายนอกอาจจะดูเป็นคนอ่อยเก่ง แพรวพราว\nแต่จริงๆแล้วเป็นคนค่อนข้างอ่อนไหว\nเป็นคนออกจะบ๊องๆ ขาดๆ เกินๆด้วยซ้ำ\nคนเกิดวันนี้ถึงจะดูอ่อยเก่งก็จริง ดูเป็นสาวฮอต หนุ่มฮอต\nแต่รักใครแล้วรักจริงจังมาก ไม่ชอบการนอกใจ\nและการถูกหักหลัง");
            tarCharacterLove.setText("เวลาคนเกิดวันพฤหัสบดีมีความรักแล้วเหมือนเมากัญชา\nอารมณ์ดีทั้งวัน และวันครบรอบ วันเกิด จำได้หมด\nตกหลุมรักคนง่าย ยิ่งถ้าเจอคนที่คุยแบบ Deep Conversation ได้\nยิ่งชอบ ชอบคนที่เป็นผู้ใหญ่ ยิ่งมีทัศนคติดีๆ\nหรือพลังบวก คนที่เกิดวันพฤหัสบดีจะมโนไปถึงขั้นแต่งงานเลย\nทั้ง ๆ ที่แค่เริ่มคุย แต่ก็ชอบความรักที่ค่อยเป็นค่อยไป\nไม่รีบนะ");
            lblPerson.setText("60%");
        } else if (rdbFri.isSelected()) {
            tarCharacter.setText("คนเกิดวันนี้ออกแนวพ่อบ้านใจกล้า ไม่เถียงหรอกนะ\nแต่อย่าให้โกรธ! เป็นคนช่างมโน ชอบเพ้อเงียบๆ\nเป็นตุเป็นตะอยู่คนเดียว และคนเกิดวันนี้เป็นคนอ่อนโยน\nเอาใจใส่แฟนมาก ต้องการให้แฟนเอาใจใส่ตัวเองเหมือนกัน\nถ้าเจอคนที่ทำให้คนเกิดวันศุกร์รู้สึกรักทั้งแฟน\nรักทั้งตัวเองหรือชอบตัวเองตอนอยู่กับแฟน\nจะเป็นอะไรที่เพอร์เฟ็กต์มาก");
            tarCharacterLove.setText("ใครชอบคนสายเปย์มาทางนี้!\nคนเกิดวันศุกร์บอกเลยว่าเปย์เก่งงงง ชอบหาอะไรทำ\nชวนแฟนทำนู่นทำนี่ อยู่ด้วยแล้วไม่มีทางเบื่อแน่นอน\nและมักจะเจอคนที่แตกต่างกันที่ อายุ เชื้อชาติ ศาสนา ฐานะฯลฯ\nแต่ไม่ค่อยสนใจเท่าไร ถ้าพร้อมจะเดินไปด้วยกันก็โอเค\nคบกันได้ยาว ๆ");
            lblPerson.setText("85%");
        } else if (rdbSatur.isSelected()) {
            tarCharacter.setText("คนที่เกิดวันเสาร์ชอบทำตัวเป็นผู้นำ อีโก้สูง บ้าพลัง\nไม่ชอบคนต่อล้อต่อเถียง ฉะนั้นคนที่นิ่งๆ สุขุมหน่อยๆ\nก็จะเข้าทางคนที่เกิดวันนี้ เป็นคนเด็ดขาด ชัดเจน ชอบก็คือชอบ\nไม่ยึกๆ ยักๆ ชอบคนเอาใจ ใส่ใจ ชอบอะไรที่เรียบง่าย\nมั่นคง ถ้ามีแฟนแล้วก็จะทุ่มสุด ๆ");
            tarCharacterLove.setText("อยากได้อะไรบอกจะจัดให้ตามที่ขอทุกอย่างยกเว้นให้ลุงลาออก\n(เอ๊ย! ไม่ใช่!)ดูแลแฟนหรือคนรักดีเว่อร์!\nเหมือนเราเป็นเจ้าหญิงหรือเจ้าชาย แต่ไม่ชอบอะไรที่จุกจิก\nชนิดว่าตามหึงตามจิกเกินเบอร์จะเบื่อมาก แต่ถึงจะไม่ชอบอะไรแบบนั้น\nคนที่เกิดวันเสาร์เวลาหึงจะน่ากลัวระดับสิบ!");
            lblPerson.setText("70%");
        } else if (rdbSun.isSelected()) {
            tarCharacter.setText("คนที่เกิดวันอาทิตย์เขาว่าเป็นคนอารมณ์ขึ้นๆ ลงๆ\nอาจจะตามอารมณ์ยากสักหน่อย เป็นคนใจกว้าง\nให้อิสระกับคนรัก แต่ถ้าเข้าโหมดจริงจังแล้วไม่ชอบอะไรเล่นๆ\nอยู่ไหน ทำอะไรกับใคร ต้องบอก ต้องรายงาน\nและถ้าชอบใครก็จะทำทุกวิถีทางเพื่อให้ได้คบ");
            tarCharacterLove.setText("พอมีแฟนแล้วโลกสดใส อะไรก็เป็นสีชมพูไปหมด\nถ้ามีแฟนจะขี้บ่นมากๆ แต่ก็เป็นเพราะรักแหละถึงบ่น\nเป็นคนรักเดียวใจเดียว คบใครก็คบทีละคน\nไม่ได้หว่านไปทั่วถ้าเทียบกับคนเกิดวันอื่นๆ\nถ้าเจอแฟนหรือคนรักที่เข้ากับครอบครัวหรือเพื่อนได้ก็ผ่านฉลุย\nเพราะชอบความรักแบบลึกซึ้ง พร้อมที่จะเป็นครอบครัวเดียวกันในอนาคต\nชอบคนพูดเพราะ ใส่ใจ ยิ้มหวาน\nถ้าสอบผ่านก็จะเสมอต้นเสมอปลายกับคนรักมาก ๆ");
            lblPerson.setText("75%");
        }//GEN-LAST:event_btnPredictActionPerformed
    }

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int option = JOptionPane.showConfirmDialog(rootPane, "Exit?");
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnPredictActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int option = JOptionPane.showConfirmDialog(rootPane, "Exit?");
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);    
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lovehoroscope.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lovehoroscope.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lovehoroscope.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lovehoroscope.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lovehoroscope().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPredict;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPerson;
    private javax.swing.JRadioButton rdbFri;
    private javax.swing.JRadioButton rdbMon;
    private javax.swing.JRadioButton rdbSatur;
    private javax.swing.JRadioButton rdbSun;
    private javax.swing.JRadioButton rdbThurs;
    private javax.swing.JRadioButton rdbTues;
    private javax.swing.JRadioButton rdbWed;
    private javax.swing.JTextArea tarCharacter;
    private javax.swing.JTextArea tarCharacterLove;
    // End of variables declaration//GEN-END:variables
}
